feat!: add transformer to filter arguments.
openedx/event-routing-backends pull request #374
Opened 2023-11-22 18:11 UTC by andrey-canon

**Description:** 
This improves the filter usability by adding the transformer to the filter arguments, basically this allows the filter client to access to extra data given by the transformer instance.

Current implementation just pass as argument the result of the decorated method, for example, the activity returned by this [method](https://github.com/openedx/event-routing-backends/blob/master/event_routing_backends/processors/xapi/event_transformers/enrollment_events.py#L30) however that activity or another result has limited information, for this example the filler would have something like 

```
   "object":{
      "id":"https://example.com/course/course-v1:edx+cs105+101_2023",
      "definition":{
         "name":{
            "en":" testing-course "
         },
         "type":"http://adlnet.gov/expapi/activities/course",
         "extensions":{
            "https://w3id.org/xapi/acrossx/extensions/type":"audit"
         }
      },
      "objectType":"Activity"
   }
```
In this case, if someone wants to get more data, for example, event_name, it's not possible, so adding the transformer instance  allows to the person who is developing the filter to  access instance methods and attributes like transformer.get_data()  or transformer.event

**Testing instructions:**

This works like another openedx-filter https://github.com/openedx/openedx-filters/

1. Define your pipeline, follow the openedx-filter instructions,finally the logic is up to you.A basic implementation could be the following
```
import logging
from openedx_filters import PipelineStep

LOGGER = logging.getLogger(__name__)

class Something(PipelineStep):

    def run_filter(self, transformer, result):
        LOGGER.info("I'm very happy with my first pipeline")
        return {
            "result": result
        }
```

2. include the configuration in your settings

```
OPEN_EDX_FILTERS_CONFIG = {
    "event_routing_backends.processors.xapi.transformer.xapi_transformer.get_actor": {
        "pipeline": ["path.to.the.class.Something"],
        "fail_silently": False,
    }
}
```
3. Raise any event and check that the pipeline logic was executed

## Note
This is a breaking change since current filters won't work with this version 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is
      finished.

2023-11-22 18:11 UTC, openedx-webhooks commented
Thanks for the pull request, @andrey-canon! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-11-27 21:44 UTC, mphilbrick211 commented
Hi @openedx/arch-bom! Is this something you could please review / merge for us?

2023-11-27 22:31 UTC, robrap commented
@andrey-canon: Is this just building on work from https://github.com/openedx/event-routing-backends/blob/master/CHANGELOG.rst#710, and should it have the same reviewers? Also, reminder to use 8.0.0 if this is a breaking change. Also, do you intend to fix anything using the older version if there are any?

2023-11-29 14:16 UTC, ziafazal approved these changes
@andrey-canon Thanks for creating this PR. Overall looks good. Could you please update the docstrings to reflect addition of `transformer` in arguments e.g docstring of  run_filter method.

2023-11-29 16:04 UTC, robrap requested changes
Please see my earlier comment and update the CHANGELOG as a minimum, as well as the version if you plan on releasing this change. Thank you.

2023-11-29 22:49 UTC, andrey-canon commented
> @andrey-canon: Is this just building on work from https://github.com/openedx/event-routing-backends/blob/master/CHANGELOG.rst#710, and should it have the same reviewers? Also, reminder to use 8.0.0 if this is a breaking change. Also, do you intend to fix anything using the older version if there are any?

This doesn't fix anything this just complements the current implementation, since after using the current feature I realized that was very hard to get some basic information in the external filters e.g event name by adding this transformer the data can be extracted easily from the transformer

2023-11-30 00:46 UTC, robrap commented on CHANGELOG.rst
> +* Add transformer argument to openedx dynamic filter.
```suggestion
* **BREAKING CHANGE**: Add transformer argument to openedx dynamic filter.
```

2023-11-30 00:50 UTC, robrap commented
@andrey-canon: Thanks for the version and changelog updates.

> This doesn't fix anything this just complements the current implementation, since after using the current feature I realized that was very hard to get some basic information in the external filters e.g event name by adding this transformer the data can be extracted easily from the transformer

In the description, you had written:

> This is a breaking change since current filters won't work with this version

I was asking if there were current filters that will be broken and need to be updated to work with this version?

2023-12-06 18:53 UTC, robrap approved these changes
Thanks for the update @andrey-canon.

[inform] See https://discuss.openedx.org/t/readthedocs-build-failures-missing-config-or-invalid-build-os/11871

Is this something you can merge, or will you need help with that?

2023-12-06 21:26 UTC, robrap commented
@andrey-canon: See this comment on the cookiecutter update: https://github.com/openedx/edx-cookiecutters/pull/419#issuecomment-1843715448. It _may_ have issues.

2023-12-06 21:33 UTC, andrey-canon commented
> @andrey-canon: See this comment on the cookiecutter update: [openedx/edx-cookiecutters#419 (comment)](https://github.com/openedx/edx-cookiecutters/pull/419#issuecomment-1843715448). It _may_ have issues.

@robrap I included the original fix however this repository has a lot of warnings that's why I had to remove the `fail_on_warning: true` and now all tests are passing

2023-12-06 22:04 UTC, robrap commented
Great. Thanks @andrey-canon. Who will be merging this? And releasing? I'll be out the rest of the week.

2023-12-06 22:18 UTC, Ian2012 approved these changes

2023-12-06 22:18 UTC, merged

2023-12-06 22:18 UTC, openedx-webhooks commented
@andrey-canon 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/event-routing-backends&entry.867055334=https://github.com/openedx/event-routing-backends/pull/374&entry.1484655318=https://github.com/andrey-canon&entry.752974735=2023-11-22+18:11&entry.1917517419=2023-12-06+22:18&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->